code --install-extension aaron-bond.better-comments
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension mikestead.dotenv
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dbaeumer.vscode-eslint
code --install-extension prisma.vscode-graphql
code --install-extension davidanson.vscode-markdownlint
code --install-extension silvenon.mdx
code --install-extension sdras.night-owl
code --install-extension christian-kohler.npm-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension octref.vetur
code --install-extension vscode-icons-team.vscode-icons